Vagrant.configure('2') do |config|

  # Configure ssh
  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  
  config.vm.box = 'centos/7'
  
  # Set up ssh connection with host machine
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys"
  
  # Install common packages
  config.vm.provision :shell, :inline => "sudo yum install -y vim git bash-complete"

  config.vm.provider 'virtualbox' do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define 'master' do |master|
    master.vm.provider 'virtualbox' do |vm|
      vm.cpus = 2
      vm.memory = 1024
      vm.name = 'master'
    end
    master.vm.hostname = 'master'
    master.vm.network "private_network", ip: '192.168.4.110'
    master.vm.network "private_network", ip: '192.168.123.130'
  end

  config.vm.define 'worker1' do |worker|
    worker.vm.provider 'virtualbox' do |vm|
      vm.cpus = 1
      vm.memory = 512
      vm.name = 'worker1'
    end
    worker.vm.hostname = 'worker1'
    worker.vm.network "private_network", ip: '192.168.4.111'
    worker.vm.network "private_network", ip: '192.168.123.131'
  end
  
  config.vm.define 'worker2' do |worker|
    worker.vm.provider 'virtualbox' do |vm|
      vm.cpus = 1
      vm.memory = 512
      vm.name = 'worker2'
    end
    worker.vm.hostname = 'worker2'
    worker.vm.network "private_network", ip: '192.168.4.112'
    worker.vm.network "private_network", ip: '192.168.123.132'
  end
  
  config.vm.define 'worker3' do |worker|
    worker.vm.provider 'virtualbox' do |vm|
      vm.cpus = 1
      vm.memory = 512
      vm.name = 'worker3'
    end
    worker.vm.hostname = 'worker3'
    worker.vm.network "private_network", ip: '192.168.4.113'
    worker.vm.network "private_network", ip: '192.168.123.133'
  end

end
